// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZ2je5wb9dmMkf7FYiktYd4_-nm3Pws8',
    appId: '1:177658533596:web:678a2085eac6dae5014619',
    messagingSenderId: '177658533596',
    projectId: 'flutter-example-af3d8',
    authDomain: 'flutter-example-af3d8.firebaseapp.com',
    storageBucket: 'flutter-example-af3d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1YuEBmYtGJzKoAvvWG1L2fZSJhNR4tJ4',
    appId: '1:177658533596:android:561d43ad327dce53014619',
    messagingSenderId: '177658533596',
    projectId: 'flutter-example-af3d8',
    storageBucket: 'flutter-example-af3d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMUYWDxy4LoX9pnsLc1PyxSslD93-5w_M',
    appId: '1:177658533596:ios:d302556d1bae4d09014619',
    messagingSenderId: '177658533596',
    projectId: 'flutter-example-af3d8',
    storageBucket: 'flutter-example-af3d8.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMUYWDxy4LoX9pnsLc1PyxSslD93-5w_M',
    appId: '1:177658533596:ios:a41d91d6b16163f3014619',
    messagingSenderId: '177658533596',
    projectId: 'flutter-example-af3d8',
    storageBucket: 'flutter-example-af3d8.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
